dist: xenial
language: cpp
before_script:
  - sudo apt-get update
  - sudo apt-get -y install libboost-test-dev doxygen graphviz
script:
  - cmake .
  - cmake --build . -- VERBOSE=1
  - cmake --build . --target test -- VERBOSE=1
  - cmake --build . --target package -- VERBOSE=1
  - doxygen ./Doxyfile
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u0xadb:$BINTRAY_API_KEY "https://api.bintray.com/content/0xadb/otus/homework/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./html
  on:
    branch: master
